[project]
name = "devops-showcase-app"
version = "0.1.0"
description = "DevOps showcase application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]==0.127.0",
    "sqlmodel==0.0.27",
    "psycopg2-binary==2.9.11",
    "opentelemetry-api==1.35.0",
    "opentelemetry-sdk==1.35.0",
    "opentelemetry-instrumentation-fastapi==0.56b0",
    "opentelemetry-exporter-otlp==1.35.0",
    "prometheus-fastapi-instrumentator==7.1.0",
    "loguru==0.7.3",
    "pydantic>=2.12.0",
    "httptools>=0.7.0",
    "grpcio>=1.75.1",
    "uvloop>=0.22.0",
    "rignore>=0.7.6"
]

[dependency-groups]
dev = [
    "coverage>=7.10.0",
    "pytest>=8.4.1",
    "testcontainers>=4.12.0",
]
