apiVersion: v2
name: devops-showcase-app
description: A Helm chart for deploying the DevOps Showcase App
type: application
version: 0.3.0

dependencies:
  - name: application
    version: 6.12.2
    repository: "https://stakater.github.io/stakater-charts"
  - name: postgresql
    condition: postgresql.enabled
    version: 18.0.17
    repository: "https://charts.bitnami.com/bitnami"
